### ISSUE TITLE
数据输入：字向量；词向量？

### ISSUE THREAD

**Issue by iwanttoknowmore** [springjean/NER-action#1]
请问，代码可以使用预训练的词向量作为输入吗，我现在有自己训练的词向量，想在NER任务检验向量的效果。

**Comment by springjean** [comment]
可以的，将词向量文件直接替换掉就可。不过项目原本使用的是字向量，直接替换成词向量的话你需要将语料替换成词的。就是你需要将训练集测试集和验证集全部换掉。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月30日(星期一) 下午5:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[springjean/NER-action] 数据输入：字向量；词向量？ (#1)

**Comment by iwanttoknowmore** [comment]
请问，将训练集替换成词的大概是什么样的格式，
例如训练集中 厦门这个词 字级别的BIO标签是  厦 B-LOC   门 I-LOC  
要是换成词级别的是 厦门 为整体给一个标签吗。

**Comment by springjean** [comment]
是的，厦门为一整个。你的词向量是什么形式就是什么形式，你的词向量如果是词语，那就需要把预料换成词语的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 晚上9:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [springjean/NER-action] 数据输入：字向量；词向量？ (#1)




 
请问，将训练集替换成词的大概是什么样的格式，
 例如训练集中 厦门这个词 字级别的BIO标签是  厦 B-LOC   门 I-LOC
 要是换成词级别的是 厦门 为整体给一个标签吗。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iwanttoknowmore** [comment]
好的，谢谢您！
